### ISSUE TITLE
Point to home page for the package

### ISSUE THREAD

**Issue by fabaff** [ooii/pySuez#1]
At the moment the `url` points to the `releases` section on Github.

https://github.com/ooii/pySuez/blob/ce176d0ab083b33c2262e0075ced23942290bc8f/setup.py#L23

This URL should be `download_url`.

**Comment by ooii** [comment]
You mean that I should put `download_url='https://github.com/ooii/pySuez/releases/tag/0.1.13' `?

**Comment by fabaff** [comment]
Yes, and let `url` point to the Github repo.
