### ISSUE TITLE
Redirect to eauxdesenart.com

### ISSUE THREAD

**Issue by schumijo** [ooii/pySuez#14]
Hello,

When I login to www.toutsurmoneau.fr, I am automatically redirected to eauxdesenart.com website.
This website is exactly the same and when I edit your BASE_URI variable, values are correctly parsed.

Is it possible to take into account this redirection in your code ?

I would like to use home assistant integration without editing python scripts.

Thanks for your work !

**Comment by Guigui37** [comment]
Hello,

Same problem here, but redirected to www.gaz-et-eaux.info.
Website www.toutsurmoneau.fr used to work few years ago, but now, each time we log on www.toutsurmoneau.fr, we get redirected to a different domain.

Thank you ! :-)
