### ISSUE TITLE
csrfToken

### ISSUE THREAD

**Issue by alexandreaudrain** [ooii/pySuez#20]
Hi, I can't get answer fron toutsurmoneau :+1:

     self._token = result.group(1)
                  ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

I think they changed the token name from _csrf_token to csrfToken (somewhere around feb. the 7th), but since I'm too bad at regex and encounter unicode problems... I can't find any solution.

Do you encounter such problems ?

**Comment by Kelesis** [comment]
Hello, I know why.. csrf token has been moved inside the web page into an utf-8 escaped string ... the line which was looking for token has to be changed to

phrase = re.compile('csrfToken\\\\u0022\\\\u003A\\\\u0022(.*)\\\\u0022,\\\\u0022')

unfortunately @ooii doesn't seem to be active anymore on this project.

**Comment by alexandreaudrain** [comment]
It works perfectly, thanx !
I was struggling with unicode…

**Comment by ooii** [comment]
Guys,
I'm sorry for not responding to these issues. I was very busy with other stuff and, to be honest, the integration was not satisfactory for me, so I stopped using it (and looking to this repo). I got some complaints recently and decided to give a look and discovered all these issues.
I'll try to bring a new and better integration that takes into consideration all the issues and sub-providers, and I'll try to make it doable from the UI. Please, be patient.
